# Basic Site Settings
locale      : "en-US"
site_theme  : "default"
custom_css:
  - assets/css/custom.css
title       : "About me"
title_separator : "-"
name        : &name "Yibing Shi"
description : &description "PhD candidate in Linguistics at the University of Cambridge"
url         : "https://yibingshi418.github.io"
baseurl     : ""
repository  : "yibingshi418/yibingshi418.github.io"

# Site Author (sidebar profile)
author:
  avatar   : "yibing.JPG"
  name     : "Yibing Shi"
  bio      : "Ph.D. at University of Cambridge"
  location : "Cambridge, U.K."
  employer : "University of Cambridge"
  email    : "ys538@cam.ac.uk"   

  googlescholar : "https://scholar.google.com.hk/citations?user=QW5E7bIAAAAJ&hl=en&oi=sra"
  linkedin      : "yibing-shi-7b417115b/?originalSubdomain=uk"
  github        : "yibingshi418"

# Publication categories
publication_category:
  papers:
    title: "Conference proceedings"
  theses:
    title: "Theses"
  conferences:
    title: "Conferences & Presentations"


# Site Settings
breadcrumbs      : false
words_per_minute : 160
future           : true
read_more        : "disabled"
talkmap_link     : false

comments:
  provider :  # disabled

atom_feed:
  hide : false

# SEO & Social (disabled)
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

twitter:
  username : &twitter
facebook:
  username :
og_image       :
og_description :

social:
  type  :
  name  :
  links : []   # ← IMPORTANT: empty social links (no icons)

# Analytics (disabled)
analytics:
  provider : "false"
  google:
    tracking_id :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - vendor
keep_files:
  - .git
  - .svn

encoding     : "utf-8"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown          : kramdown
highlighter       : rouge
lsi               : false
excerpt_separator : "\n\n"
incremental       : false

# Markdown Processing
kramdown:
  input          : GFM
  hard_wrap      : false
  auto_ids       : true
  footnote_nr    : 1
  entity_output  : as_char
  toc_levels     : 1..6
  smart_quotes   : lsquo,rsquo,ldquo,rdquo
  enable_coderay : false

# Collections – only publications enabled
collections:
  publications:
    output    : true
    permalink : /:collection/:path/

# Defaults
defaults:
  - scope:
      path : ""
      type : pages
    values:
      layout         : single
      author_profile : true

  - scope:
      path : ""
      type : publications
    values:
      layout         : single
      author_profile : true
      share          : true
      comments       : false

# Sass/SCSS
sass:
  sass_dir : _sass
  style    : compressed

# Outputting
permalink : /:categories/:title/
timezone  : Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type : liquid
  path : /categories/
tag_archive:
  type : liquid
  path : /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
